DROP TABLE IF EXISTS mpa, films, users, film_likes, genres, film_genres, friendships;

CREATE TABLE mpa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER,
    mpa_rating_id INTEGER REFERENCES mpa(id)
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR,
    login VARCHAR,
    name VARCHAR,
    birthday DATE
);

CREATE TABLE film_likes (
    film_id INTEGER REFERENCES films(id),
    user_id INTEGER REFERENCES users(id),
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

CREATE TABLE film_genres (
    film_id INTEGER REFERENCES films(id),
    genre_id INTEGER REFERENCES genres(id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE friendships (
    user_id INTEGER REFERENCES users(id),
    friend_id INTEGER REFERENCES users(id),
    PRIMARY KEY (user_id, friend_id)
);